debug: false

server:
  error:
    whitelabel:
      enabled: false
  max-http-header-size: 8KB
  port: ${NNS_CORE_SERVER_PORT}

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: ${NNS_CORE_DB_URL}
    username: ${NNS_CORE_SQL_USER}
    password: ${NNS_CORE_SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

bucket4j:
  enabled: true
  filters:
  - cache-name: rate-limit-buckets
    filter-order: 1
    url: .*
    http-response-body: '{ "status": 429, "error": "Too Many Requests", "message": "Too Many Requests" }'
    rate-limits:
    - bandwidths:
      - capacity: 500
        time: 1
        unit: seconds
